"""renamed current field

Revision ID: 9ad5d9cb04f2
Revises: 1923051847dd
Create Date: 2019-09-24 19:26:15.820092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad5d9cb04f2'
down_revision = '1923051847dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('livemember', sa.BOOLEAN(), nullable=True))
    op.drop_column('user', 'current')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current', sa.BOOLEAN(), nullable=True))
    op.drop_column('user', 'livemember')
    # ### end Alembic commands ###
