"""new fields in user model

Revision ID: 07b17033881e
Revises: 34fe03a8f7ab
Create Date: 2019-09-12 14:12:24.568329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b17033881e'
down_revision = '34fe03a8f7ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('club', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_club'), 'user', ['club'], unique=False)
    op.drop_index('ix_user_forename', table_name='user')
    op.create_index(op.f('ix_user_forename'), 'user', ['forename'], unique=False)
    op.drop_index('ix_user_surname', table_name='user')
    op.create_index(op.f('ix_user_surname'), 'user', ['surname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_surname'), table_name='user')
    op.create_index('ix_user_surname', 'user', ['surname'], unique=1)
    op.drop_index(op.f('ix_user_forename'), table_name='user')
    op.create_index('ix_user_forename', 'user', ['forename'], unique=1)
    op.drop_index(op.f('ix_user_club'), table_name='user')
    op.drop_column('user', 'club')
    # ### end Alembic commands ###
