"""new fields in user model

Revision ID: 34fe03a8f7ab
Revises: 340792cea023
Create Date: 2019-09-12 12:49:09.116673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34fe03a8f7ab'
down_revision = '340792cea023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address1', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('address2', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('address3', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('adminuser', sa.BOOLEAN(), nullable=True))
    op.add_column('user', sa.Column('coach', sa.BOOLEAN(), nullable=True))
    op.add_column('user', sa.Column('forename', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('next_of_kin_name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('next_of_kin_name2', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('next_of_kin_num', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('next_of_kin_num2', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('nickname', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('postcode', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('sessionmanager', sa.BOOLEAN(), nullable=True))
    op.add_column('user', sa.Column('superuser', sa.BOOLEAN(), nullable=True))
    op.add_column('user', sa.Column('surname', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('treasurer', sa.BOOLEAN(), nullable=True))
    op.create_index(op.f('ix_user_forename'), 'user', ['forename'], unique=True)
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=True)
    op.create_index(op.f('ix_user_surname'), 'user', ['surname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_surname'), table_name='user')
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.drop_index(op.f('ix_user_forename'), table_name='user')
    op.drop_column('user', 'treasurer')
    op.drop_column('user', 'surname')
    op.drop_column('user', 'superuser')
    op.drop_column('user', 'sessionmanager')
    op.drop_column('user', 'postcode')
    op.drop_column('user', 'nickname')
    op.drop_column('user', 'next_of_kin_num2')
    op.drop_column('user', 'next_of_kin_num')
    op.drop_column('user', 'next_of_kin_name2')
    op.drop_column('user', 'next_of_kin_name')
    op.drop_column('user', 'forename')
    op.drop_column('user', 'coach')
    op.drop_column('user', 'adminuser')
    op.drop_column('user', 'address3')
    op.drop_column('user', 'address2')
    op.drop_column('user', 'address1')
    # ### end Alembic commands ###
