"""new relationship club to user

Revision ID: 4f1c56be0c49
Revises: f8809e061e40
Create Date: 2019-09-17 23:13:43.762144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1c56be0c49'
down_revision = 'f8809e061e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_club', table_name='user')
    op.create_foreign_key(None, 'user', 'club', ['club'], ['clubnum'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_index('ix_user_club', 'user', ['club'], unique=False)
    # ### end Alembic commands ###
