"""new table club

Revision ID: 5ff76ba76db1
Revises: 7c3b81f68073
Create Date: 2019-09-17 21:25:44.727923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff76ba76db1'
down_revision = '7c3b81f68073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clubnum', sa.Integer(), nullable=True),
    sa.Column('usernum', sa.Integer(), nullable=True),
    sa.Column('logo', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['usernum'], ['user.usernum'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club')
    # ### end Alembic commands ###
