"""new fields in user model

Revision ID: 7c3b81f68073
Revises: a8ef856dc567
Create Date: 2019-09-12 15:00:54.311464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3b81f68073'
down_revision = 'a8ef856dc567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('category', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'category')
    # ### end Alembic commands ###
