"""new fields in user model

Revision ID: a8ef856dc567
Revises: 07b17033881e
Create Date: 2019-09-12 14:55:09.579745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ef856dc567'
down_revision = '07b17033881e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current', sa.BOOLEAN(), nullable=True))
    op.add_column('user', sa.Column('member_expire', sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'member_expire')
    op.drop_column('user', 'current')
    # ### end Alembic commands ###
