"""revert current

Revision ID: e9b30b10b948
Revises: 1923051847dd
Create Date: 2019-09-24 19:36:48.762751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b30b10b948'
down_revision = '1923051847dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'livemember')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('livemember', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
