"""initial version

Revision ID: 2da1d950f91f
Revises: 
Create Date: 2019-09-18 17:47:58.123315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da1d950f91f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usernum', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('nickname', sa.String(length=30), nullable=True),
    sa.Column('forename', sa.String(length=30), nullable=True),
    sa.Column('surname', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('current', sa.BOOLEAN(), nullable=True),
    sa.Column('member_expire', sa.DATE(), nullable=True),
    sa.Column('category', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('dob', sa.DATE(), nullable=True),
    sa.Column('address1', sa.String(length=30), nullable=True),
    sa.Column('address2', sa.String(length=30), nullable=True),
    sa.Column('address3', sa.String(length=30), nullable=True),
    sa.Column('postcode', sa.String(length=8), nullable=True),
    sa.Column('next_of_kin_name', sa.String(length=64), nullable=True),
    sa.Column('next_of_kin_num', sa.Integer(), nullable=True),
    sa.Column('next_of_kin_name2', sa.String(length=64), nullable=True),
    sa.Column('next_of_kin_num2', sa.Integer(), nullable=True),
    sa.Column('superuser', sa.BOOLEAN(), nullable=True),
    sa.Column('adminuser', sa.BOOLEAN(), nullable=True),
    sa.Column('coach', sa.BOOLEAN(), nullable=True),
    sa.Column('treasurer', sa.BOOLEAN(), nullable=True),
    sa.Column('sessionmanager', sa.BOOLEAN(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_forename'), 'user', ['forename'], unique=False)
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=True)
    op.create_index(op.f('ix_user_surname'), 'user', ['surname'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_index(op.f('ix_user_usernum'), 'user', ['usernum'], unique=True)
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clubnum', sa.Integer(), nullable=True),
    sa.Column('clubname', sa.String(length=140), nullable=True),
    sa.Column('usernum', sa.Integer(), nullable=True),
    sa.Column('logo', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['usernum'], ['user.usernum'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('followers')
    op.drop_table('club')
    op.drop_index(op.f('ix_user_usernum'), table_name='user')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_surname'), table_name='user')
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.drop_index(op.f('ix_user_forename'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
