"""session table

Revision ID: 45d73f6bb38f
Revises: 1923051847dd
Create Date: 2019-09-26 15:47:39.770627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d73f6bb38f'
down_revision = '1923051847dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club', sa.Integer(), nullable=True),
    sa.Column('sessionname', sa.String(length=80), nullable=True),
    sa.Column('childcost', sa.Integer(), nullable=True),
    sa.Column('adultcost', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club'], ['club.clubnum'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'livemember')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('livemember', sa.BOOLEAN(), nullable=True))
    op.drop_table('session')
    # ### end Alembic commands ###
